// Builds the Hushlane logo from one source: the mark (geometry below) and the
// wordmark outlined from Unbounded Bold. Writes the inline-SVG path module used
// by the site, the favicon and the brand exports in public/brand.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'
import { Resvg } from '@resvg/resvg-js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const INK = '#0E0B1A'
const BG = '#CDBDFF'

// Mark on a 32 grid: one lane in, the pool block, three lanes out.
const r = (x, y, w, h, rad) =>
  `M${x + rad} ${y}H${x + w - rad}A${rad} ${rad} 0 0 1 ${x + w} ${y + rad}V${y + h - rad}A${rad} ${rad} 0 0 1 ${x + w - rad} ${y + h}H${x + rad}A${rad} ${rad} 0 0 1 ${x} ${y + h - rad}V${y + rad}A${rad} ${rad} 0 0 1 ${x + rad} ${y}Z`
// Pill along a segment, width w.
const pill = (x1, y1, x2, y2, w) => {
  const len = Math.hypot(x2 - x1, y2 - y1)
  const nx = (-(y2 - y1) / len) * (w / 2)
  const ny = ((x2 - x1) / len) * (w / 2)
  const f = (n) => +n.toFixed(3)
  const h = w / 2
  return `M${f(x1 + nx)} ${f(y1 + ny)}L${f(x2 + nx)} ${f(y2 + ny)}A${h} ${h} 0 0 0 ${f(x2 - nx)} ${f(y2 - ny)}L${f(x1 - nx)} ${f(y1 - ny)}A${h} ${h} 0 0 0 ${f(x1 + nx)} ${f(y1 + ny)}Z`
}
const markPath = [
  pill(2.5, 16, 6.5, 16, 5), // lane in
  r(10, 1, 10, 30, 3), // shielded pool
  pill(25.5, 9.5, 29.5, 4.5, 5), // lanes out, fanning to separate wallets
  pill(25.5, 16, 30, 16, 5),
  pill(25.5, 22.5, 29.5, 27.5, 5),
].join('')

// Wordmark
const fontFile = path.join(root, 'node_modules/@fontsource/unbounded/files/unbounded-latin-700-normal.woff')
const buf = fs.readFileSync(fontFile)
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const SIZE = 32
const TRACK = -0.02 * SIZE
let x = 0
const glyphPaths = []
for (const ch of 'hushlane') {
  const g = font.charToGlyph(ch)
  const p = g.getPath(x, 0, SIZE)
  glyphPaths.push(p.toPathData(2))
  x += (g.advanceWidth / font.unitsPerEm) * SIZE + TRACK
}
const wordD = glyphPaths.join('')
// measure bbox
const tmp = new opentype.Path()
tmp.commands = glyphPaths.flatMap((_, i) => {
  const g = font.charToGlyph('hushlane'[i])
  let xx = 0
  for (let k = 0; k < i; k++) xx += (font.charToGlyph('hushlane'[k]).advanceWidth / font.unitsPerEm) * SIZE + TRACK
  return g.getPath(xx, 0, SIZE).commands
})
const bb = tmp.getBoundingBox()
const wordW = bb.x2 - bb.x1
const wordH = bb.y2 - bb.y1

// Lockup: mark a little taller than the wordmark, centred on it, gap 10.
const markScale = (wordH * 1.25) / 32
const gap = 10
const markH = 32 * markScale
const lockW = 32 * markScale + gap + wordW
const lockH = markH
const tx = 32 * markScale + gap - bb.x1
const ty = (markH - wordH) / 2 - bb.y1
const lockupInner = `<path d="${markPath}" transform="scale(${markScale.toFixed(4)})"/><path d="${wordD}" transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)})"/>`
const lockupSvg = (fill) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${lockW.toFixed(2)} ${lockH.toFixed(2)}" fill="${fill}">${lockupInner}</svg>`
const markSvg = (fill, bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-4 -4 40 40">${bg ? `<rect x="-4" y="-4" width="40" height="40" rx="9" fill="${bg}"/>` : ''}<path fill="${fill}" d="${markPath}"/></svg>`

// TS module for inline use
const mod = `// Generated by scripts/build-logo.mjs. Do not edit by hand.
export const MARK_PATH = ${JSON.stringify(markPath)}
export const WORD_PATH = ${JSON.stringify(wordD)}
export const LOCKUP = {
  width: ${lockW.toFixed(2)},
  height: ${lockH.toFixed(2)},
  markScale: ${markScale.toFixed(4)},
  wordX: ${tx.toFixed(2)},
  wordY: ${ty.toFixed(2)},
}
`
fs.mkdirSync(path.join(root, 'src/components/brand'), { recursive: true })
fs.writeFileSync(path.join(root, 'src/components/brand/logoPaths.ts'), mod)

// Exports
const brandDir = path.join(root, 'public/brand')
fs.mkdirSync(brandDir, { recursive: true })
fs.writeFileSync(path.join(brandDir, 'logo.svg'), lockupSvg(INK))
fs.writeFileSync(path.join(brandDir, 'logo-inverted.svg'), lockupSvg(BG))
fs.writeFileSync(path.join(brandDir, 'mark.svg'), markSvg(INK))
fs.writeFileSync(path.join(root, 'public/favicon.svg'), markSvg(BG, INK))

// 500x500 PNGs, lockup centred with ~12% padding
const S = 500
const pad = S * 0.12
const scale = (S - 2 * pad) / lockW
const placed = (bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">${bg ? `<rect width="${S}" height="${S}" fill="${bg}"/>` : ''}<g fill="${INK}" transform="translate(${pad} ${(S - lockH * scale) / 2}) scale(${scale.toFixed(5)})">${lockupInner}</g></svg>`
for (const [name, bg] of [['logo-500.png', BG], ['logo-500-transparent.png', null]]) {
  const png = new Resvg(placed(bg), { fitTo: { mode: 'original' } }).render().asPng()
  fs.writeFileSync(path.join(brandDir, name), png)
}
console.log('lockup', lockW.toFixed(1), 'x', lockH.toFixed(1), 'markScale', markScale.toFixed(3))
